### ISSUE TITLE
PHP 8.2 & Laravel 11: gzinflate() data error: Creation of dynamic property $destination is deprecated.

### ISSUE THREAD

**Issue by matthewdanepeavoy** [codegreencreative/laravel-samlidp#145]
Using PHP 8.2 & Laravel 11

Getting on route /saml/logout
```ErrorException: gzinflate(): data error```

Also a log warning
```Creation of dynamic property CodeGreenCreative\SamlIdp\Jobs\SamlSlo::$destination is deprecated in /home/forge/mysite.com/vendor/codegreencreative/laravel-samlidp/src/Jobs/SamlSlo.php on li…```

Looks like dynamic properties were deprecated in PHP 8.2
https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by matthewdanepeavoy** [comment]
I've been tracking another error, that I believe is the same issue.

Error thrown: 
```CodeGreenCreative\SamlIdp\Exceptions\DestinationMissingException: ######################= does not have a destination set in config file.```

But just seeing a couple of log warnings that are attached to this:

```log.warning
Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated in /home/forge/accounts.musicplay.ca/vendor/codegreencreative/laravel-samlidp/src/Exceptions/DestinationMissing…```

and one more
```Creation of dynamic property CodeGreenCreative\SamlIdp\Jobs\SamlSso::$guard is deprecated in /home/forge/accounts.musicplay.ca/vendor/codegreencreative/laravel-samlidp/src/Jobs/SamlSso.php on line 47```

**Comment by upwebdesign** [comment]
@matthewdanepeavoy, I just pushed some code to the master branch to address the warning `Creation of dynamic property`. The `DestinationMissingException` you are receiving indicates you are missing a destination in the config file. Is it missing? I also address the `Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated` exception you mentioned.

I don't have a project I can easily test with these changes. I will need your help to ensure this is not breaking anything. Let me know if you are able to confirm the updates are working as expected.

**Comment by matthewdanepeavoy** [comment]
@upwebdesign - Thanks for tackling those so quickly! I'll do my best to validate the Log warnings are resolved here shortly. 

Regarding the ```DestinationMissingException```, we have validated the destination is set correctly as far as we can tell. The SAML login for the destination that's throwing the error is still working in production, and the error is only being thrown once every couple of days.

I will say the error first started to appear when we upgraded from PHP 8.1 to 8.2, but we also added a migration with another SAML SP in that update.

I'll do some more validation here and let you know of any updates!

**Comment by matthewdanepeavoy** [comment]
Yes can confirm everything appears to be working as expected on my local!

**Comment by upwebdesign** [comment]
@matthewdanepeavoy I created a new release with the updates from the other day. After reading the thread, I'm unsure if anything else needs to be addressed. I have not used this package with PHP 8.3; thanks for reporting the issues. Please let me know if there is anything else so I can close this issue.
